version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <ECR_URI>

  build:
    commands:
      - docker build -t demo-app .
      - docker tag demo-app:latest <ECR_URI>:latest

  post_build:
    commands:
      - docker push <ECR_URI>:latest
      - printf '[{"name":"demo-app","imageUri":"%s"}]' <ECR_URI>:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
